### ISSUE TITLE
add QR code with Slack link

### ISSUE THREAD

**Issue by annamorgiel** [WTMBerlin/WTMBApp#50]

**Comment by mariobodemann** [comment]
|name|image|
|--------|----------|
| website | ![wtmqr](https://user-images.githubusercontent.com/1162562/58659578-9b0e2400-8323-11e9-9ddf-af8782906d93.png)
| slackin | ![wtmslackqr](https://user-images.githubusercontent.com/1162562/58659579-9ba6ba80-8323-11e9-855b-22c0356bf0ac.png)
