### ISSUE TITLE
Fix grade issues

### ISSUE THREAD

**Issue by annamorgiel** [WTMBerlin/WTMBApp#74]

**Comment by alisen** [comment]
What kind of error we have in here?

**Comment by annamorgiel** [comment]
@alisen 
https://github.com/WTMBerlin/WTMBApp/pull/73
<img width="884" alt="Screenshot 2020-03-26 at 14 53 19" src="https://user-images.githubusercontent.com/18116883/77654623-9630f580-6f71-11ea-8c50-fbbd80524dfa.png">

**Comment by annamorgiel** [comment]
I made an attempt of solving those conflicts it but the hamburger icon from the upper left corner disappeared so it requires some more care

**Comment by alisen** [comment]
I can help with that tonight at co-learning.
